// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteConnection(arg1) {
  return window['go']['service']['ConnectionStorageService']['DeleteConnection'](arg1);
}

export function ListConnection() {
  return window['go']['service']['ConnectionStorageService']['ListConnection']();
}

export function SaveConnection(arg1) {
  return window['go']['service']['ConnectionStorageService']['SaveConnection'](arg1);
}

export function Startup(arg1) {
  return window['go']['service']['ConnectionStorageService']['Startup'](arg1);
}

export function UpdateConnection(arg1) {
  return window['go']['service']['ConnectionStorageService']['UpdateConnection'](arg1);
}
