// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';
import {context} from '../models';

export function DeleteConnection(arg1:number):Promise<number>;

export function ListConnection():Promise<Array<service.ConnectionConfig>>;

export function SaveConnection(arg1:service.ConnectionConfig):Promise<number>;

export function Startup(arg1:context.Context):Promise<void>;

export function UpdateConnection(arg1:service.ConnectionConfig):Promise<number>;
