// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Check(arg1) {
  return window['go']['service']['RestSqlService']['Check'](arg1);
}

export function CountChildTable(arg1, arg2, arg3, arg4) {
  return window['go']['service']['RestSqlService']['CountChildTable'](arg1, arg2, arg3, arg4);
}

export function CountData(arg1, arg2, arg3, arg4) {
  return window['go']['service']['RestSqlService']['CountData'](arg1, arg2, arg3, arg4);
}

export function DescTable(arg1, arg2, arg3) {
  return window['go']['service']['RestSqlService']['DescTable'](arg1, arg2, arg3);
}

export function DoPost(arg1, arg2) {
  return window['go']['service']['RestSqlService']['DoPost'](arg1, arg2);
}

export function ListChildTable(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['service']['RestSqlService']['ListChildTable'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ListDatabases(arg1) {
  return window['go']['service']['RestSqlService']['ListDatabases'](arg1);
}

export function ListSuperTable(arg1, arg2, arg3) {
  return window['go']['service']['RestSqlService']['ListSuperTable'](arg1, arg2, arg3);
}

export function PageData(arg1, arg2, arg3, arg4) {
  return window['go']['service']['RestSqlService']['PageData'](arg1, arg2, arg3, arg4);
}

export function SqlQuery(arg1, arg2) {
  return window['go']['service']['RestSqlService']['SqlQuery'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['service']['RestSqlService']['Startup'](arg1);
}
