// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Post(arg1) {
  return window['go']['service']['RestSqlService']['Post'](arg1);
}

export function Startup(arg1) {
  return window['go']['service']['RestSqlService']['Startup'](arg1);
}
