// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Check(arg1) {
  return window['go']['service']['SqlService']['Check'](arg1);
}

export function DescTable(arg1, arg2, arg3) {
  return window['go']['service']['SqlService']['DescTable'](arg1, arg2, arg3);
}

export function Greet(arg1) {
  return window['go']['service']['SqlService']['Greet'](arg1);
}

export function ListChildTable(arg1, arg2, arg3, arg4) {
  return window['go']['service']['SqlService']['ListChildTable'](arg1, arg2, arg3, arg4);
}

export function ListDatabases(arg1) {
  return window['go']['service']['SqlService']['ListDatabases'](arg1);
}

export function ListSuperTable(arg1, arg2, arg3) {
  return window['go']['service']['SqlService']['ListSuperTable'](arg1, arg2, arg3);
}

export function PageData1(arg1, arg2, arg3, arg4) {
  return window['go']['service']['SqlService']['PageData1'](arg1, arg2, arg3, arg4);
}

export function SqlQuery(arg1, arg2) {
  return window['go']['service']['SqlService']['SqlQuery'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['service']['SqlService']['Startup'](arg1);
}
