// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';
import {context} from '../models';

export function Check(arg1:string):Promise<any>;

export function DescTable(arg1:service.ConnectionConfig,arg2:string,arg3:string):Promise<Array<service.TableField>>;

export function Greet(arg1:string):Promise<string>;

export function ListChildTable(arg1:service.ConnectionConfig,arg2:string,arg3:string,arg4:string):Promise<Array<string>>;

export function ListDatabases(arg1:service.ConnectionConfig):Promise<Array<string>>;

export function ListSuperTable(arg1:service.ConnectionConfig,arg2:string,arg3:string):Promise<Array<string>>;

export function PageData1(arg1:service.ConnectionConfig,arg2:string,arg3:string,arg4:service.Query):Promise<service.PageData>;

export function SqlQuery(arg1:service.ConnectionConfig,arg2:string):Promise<service.PageData>;

export function Startup(arg1:context.Context):Promise<void>;
