// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Check(arg1:string):Promise<any>;

export function Greet(arg1:string):Promise<string>;

export function ListChildTable(arg1:string,arg2:string):Promise<Array<string>>;

export function ListDatabases():Promise<Array<string>>;

export function ListSuperTable(arg1:string):Promise<Array<string>>;

export function PageData(arg1:string,arg2:string):Promise<Array<any>>;

export function PageData1(arg1:string,arg2:string):Promise<main.PageData>;
