// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Check(arg1) {
  return window['go']['main']['App']['Check'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListChildTable(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListChildTable'](arg1, arg2, arg3);
}

export function ListDatabases(arg1) {
  return window['go']['main']['App']['ListDatabases'](arg1);
}

export function ListSuperTable(arg1, arg2) {
  return window['go']['main']['App']['ListSuperTable'](arg1, arg2);
}

export function PageData1(arg1, arg2, arg3) {
  return window['go']['main']['App']['PageData1'](arg1, arg2, arg3);
}
